### ISSUE TITLE
Got exception when needed to restart

### ISSUE THREAD

**Issue by karserasl** [cascandaliato/docker-restarter#3]
`restarter  | 2023-09-24T12:30:02.509038316Z Traceback (most recent call last):
restarter  | 2023-09-24T12:30:02.509065623Z   File "/usr/src/app/./restarter.py", line 32, in <module>
restarter  | 2023-09-24T12:30:02.509143644Z     service = event["Actor"]["Attributes"]["com.docker.compose.service"]
restarter  | 2023-09-24T12:30:02.509219177Z               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
restarter  | 2023-09-24T12:30:02.509233587Z KeyError: 'com.docker.compose.service'`

**Comment by karserasl** [comment]
Im using socket-proxy for docker host

`restarter:
    <<: *common-keys-core # See EXTENSION FIELDS at the top
    image: ghcr.io/cascandaliato/docker-restarter
    container_name: restarter
    networks:
      - socket_proxy
      - t2_proxy
    environment:
      <<: *default-tz-puid-pgid
      DOCKER_HOST: tcp://socket-proxy:2375`

**Comment by cascandaliato** [comment]
I pushed a fix (0c6057ace05bf9c2ae4750c3b1046daafb5f7abe). You probably started or stopped a container defined outside of a `docker compose` file.

Is Tecnativa/docker-socket-proxy the proxy you are talking about? If so, this project needs the following permissions: `EVENTS` (enabled by default?), `CONTAINERS`, `POST`, `ALLOW_RESTARTS`.

**Comment by karserasl** [comment]
Thanks alot
Gonna try

**Comment by karserasl** [comment]
I think using ALLOW_RESTARTS=1 and the latest version fixed everything

Great work

**Comment by karserasl** [comment]
Talked too fast.
Im getting this exception now.

`24/09/2023
6:01:52 pm
Restarting the following container(s) in 10 seconds because container qbittorrent (re)started: cross-seed, cross-seed-search
24/09/2023
6:33:28 pm
Restarting the following container(s) in 10 seconds because container gluetun (re)started: autobrr, joal, portcheck, qbittorrent, thelounge
24/09/2023
6:33:29 pm
Traceback (most recent call last):
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
24/09/2023
6:33:29 pm
    response.raise_for_status()
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
24/09/2023
6:33:29 pm
    raise HTTPError(http_error_msg, response=self)
24/09/2023
6:33:29 pm
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://socket-proxy:2375/v1.43/containers/4f6a65c0047b48d46bc1a962696dea9226fc7f5a7938bb81c815755e0ec0d6c8/restart?t=10
24/09/2023
6:33:29 pm
24/09/2023
6:33:29 pm
The above exception was the direct cause of the following exception:
24/09/2023
6:33:29 pm
24/09/2023
6:33:29 pm
Traceback (most recent call last):
24/09/2023
6:33:29 pm
  File "/usr/src/app/./restarter.py", line 40, in <module>
24/09/2023
6:33:29 pm
    docker_client.containers.get(depender).restart()
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/models/containers.py", line 395, in restart
24/09/2023
6:33:29 pm
    return self.client.api.restart(self.id, **kwargs)
24/09/2023
6:33:29 pm
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
24/09/2023
6:33:29 pm
    return f(self, resource_id, *args, **kwargs)
24/09/2023
6:33:29 pm
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/api/container.py", line 1089, in restart
24/09/2023
6:33:29 pm
    self._raise_for_status(res)
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
24/09/2023
6:33:29 pm
    raise create_api_error_from_http_exception(e) from e
24/09/2023
6:33:29 pm
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
24/09/2023
6:33:29 pm
  File "/usr/local/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
24/09/2023
6:33:29 pm
    raise cls(e, response=response, explanation=explanation) from e
24/09/2023
6:33:29 pm
docker.errors.APIError: 500 Server Error for http://socket-proxy:2375/v1.43/containers/4f6a65c0047b48d46bc1a962696dea9226fc7f5a7938bb81c815755e0ec0d6c8/restart?t=10: Internal Server Error ("Cannot restart container 4f6a65c0047b48d46bc1a962696dea9226fc7f5a7938bb81c815755e0ec0d6c8: No such container: c6205526a4ce82f0d4ff8b090d1138d701ecf9910dd571e02a5ab221004b066d")`

**Comment by cascandaliato** [comment]
I've added more log traces. The code doesn't expect (yet) any container to disappear so it won't work if there are services that remove containers (watchtower?) but I suspect it's something else because the proxy API is logging two different container ids in the same error message:

> docker.errors.APIError: 500 Server Error for http://socket-proxy:2375/v1.43/containers/4f6a65c0047b48d46bc1a962696dea9226fc7f5a7938bb81c815755e0ec0d6c8/restart?t=10: Internal Server Error ("Cannot restart container **4f6a65c0047b48d46bc1a962696dea9226fc7f5a7938bb81c815755e0ec0d6c8**: No such container: **c6205526a4ce82f0d4ff8b090d1138d701ecf9910dd571e02a5ab221004b066d**")

Do you mind trying again and sharing the container logs? Thank you for your patience.

**Comment by vdrover** [comment]
Just adding a note that watchtower support would be wonderful.

**Comment by karserasl** [comment]
Yeah, it was the watchtower that updated Gluetun.
So, that's the main problem.

Gluetun pushed a new release and Watchtower updates it, which caused the whole stack depending on it to lose connection.

**Comment by cascandaliato** [comment]
Ok, that makes sense. I'll make the script handle this case and only log an error if a container is not available anymore when we try to restart it, for example because watchtower has updated it, the stack has been rebuilt or the user just removed it with `docker rm`.

**Comment by cascandaliato** [comment]
After commit 7295fcaa4b8b71f648430fd1ba5a6a984a5fd209 I don't expect the container to crash if it's trying to restart a container while watchtower is removing and updating it. Please give it a try when possible.

**Comment by karserasl** [comment]
im still seeing this

```bash
restarter  | 2023-09-28T15:08:38.071354033Z Restarting container qbittorrent (id d2543234000c, service qbittorrent)
restarter  | 2023-09-28T15:08:49.117722348Z Could not restart container qbittorrent (id d2543234000c, service qbittorrent) because of error: 500 Server Error for http://socket-proxy:2375/v1.43/containers/d2543234000cc6be03349c23270e65c22135499cdfa6cbd8a1703ac4e2f95406/restart?t=10: Internal Server Error ("Cannot restart container d2543234000cc6be03349c23270e65c22135499cdfa6cbd8a1703ac4e2f95406: No such container: a7a0622a5331c1e838b668c6e7c5ad808c0ca8f78213f95eec29e3d07331b6e6")
```

**Comment by cascandaliato** [comment]
Do you know if watchtower also updated the qbittorrent container?

Can you please run these two commands and share the output:
```
docker inspect d2543234000cc6be03349c23270e65c22135499cdfa6cbd8a1703ac4e2f95406 --format "{{.Name}}"
docker inspect a7a0622a5331c1e838b668c6e7c5ad808c0ca8f78213f95eec29e3d07331b6e6 --format "{{.Name}}"
```

**Comment by cascandaliato** [comment]
Neverming, I have replicated the issue so there is no need to collect logs, etc. It's the same issue qdm12/deunhealth#11 that Quentin has been working on. I'll read his notes and see if I can do my own implementation.
